### ISSUE TITLE
symbolic link doesn't work

### ISSUE THREAD

**Issue by Textra2** [julianschuler/keyboards#1]
For me, it is not working via the symbolic link. I have to copy paste the files from ergomin/qmk to qmk/ergomin. I'm using Ubuntu 20.04.

**Comment by julianschuler** [comment]
I am unable to reproduce this with neither Linux Mint nor Arch Linux.

Please make sure to use absolute paths when working with `ln`. Also pay close attention to the order of the target and symlink.
